name: koin
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' 

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0 

flutter:
  uses-material-design: true

  assets:
    - asset/img/icon/

  fonts:
    - family: GapyeongHanseokbong
      fonts:
        - asset: asset/fonts/GapyeongHanseokbongR.otf
          weight: 300
        - asset: asset/fonts/GapyeongHanseokbongB.otf
          weight: 700
          
    - family: Pretendard
      fonts:
        - asset: asset/fonts/Pretendard-Regular.otf
          weight: 400
        - asset: asset/fonts/Pretendard-Medium.otf
          weight: 500
        - asset: asset/fonts/Pretendard-SemiBold.otf
          weight: 600