// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD_bEXtp7ECUf344VMVRYxMTQStF3R_q0',
    appId: '1:160229794752:web:e83273fadf01a20f56de25',
    messagingSenderId: '160229794752',
    projectId: 'junwoo-a626c',
    authDomain: 'junwoo-a626c.firebaseapp.com',
    storageBucket: 'junwoo-a626c.firebasestorage.app',
    measurementId: 'G-N5QBDXHR79',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcn8-BXc43Lpcc918M7J1N_BAdzMxaqJI',
    appId: '1:160229794752:android:26905330830eb36256de25',
    messagingSenderId: '160229794752',
    projectId: 'junwoo-a626c',
    storageBucket: 'junwoo-a626c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCM61HaS9u8v_AeCeuKXRdrKr4ODAMMtyQ',
    appId: '1:160229794752:ios:faf3df466fe71a9456de25',
    messagingSenderId: '160229794752',
    projectId: 'junwoo-a626c',
    storageBucket: 'junwoo-a626c.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCM61HaS9u8v_AeCeuKXRdrKr4ODAMMtyQ',
    appId: '1:160229794752:ios:faf3df466fe71a9456de25',
    messagingSenderId: '160229794752',
    projectId: 'junwoo-a626c',
    storageBucket: 'junwoo-a626c.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBD_bEXtp7ECUf344VMVRYxMTQStF3R_q0',
    appId: '1:160229794752:web:6657cd7d88ac0c9e56de25',
    messagingSenderId: '160229794752',
    projectId: 'junwoo-a626c',
    authDomain: 'junwoo-a626c.firebaseapp.com',
    storageBucket: 'junwoo-a626c.firebasestorage.app',
    measurementId: 'G-14DGQL5QGY',
  );

}